// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA10qXeM4sFDF8VzxThJ1adw_5dnuYsVj0',
    appId: '1:679859734578:web:0aad12763eaed14abf942b',
    messagingSenderId: '679859734578',
    projectId: 'sample-chatapp-38eae',
    authDomain: 'sample-chatapp-38eae.firebaseapp.com',
    storageBucket: 'sample-chatapp-38eae.appspot.com',
    measurementId: 'G-HS52PEF7PP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARo6S2Xx_jn82k2z1brYWBhuDACJOmd7s',
    appId: '1:679859734578:android:394707570f2b67f7bf942b',
    messagingSenderId: '679859734578',
    projectId: 'sample-chatapp-38eae',
    storageBucket: 'sample-chatapp-38eae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOFInx-74kk55DMfAlxYTaOvySBK2hsRM',
    appId: '1:679859734578:ios:d2cee5771d5e8423bf942b',
    messagingSenderId: '679859734578',
    projectId: 'sample-chatapp-38eae',
    storageBucket: 'sample-chatapp-38eae.appspot.com',
    iosBundleId: 'com.example.sampleChatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOFInx-74kk55DMfAlxYTaOvySBK2hsRM',
    appId: '1:679859734578:ios:cea94c6d821cf88dbf942b',
    messagingSenderId: '679859734578',
    projectId: 'sample-chatapp-38eae',
    storageBucket: 'sample-chatapp-38eae.appspot.com',
    iosBundleId: 'com.example.sampleChatapp.RunnerTests',
  );
}
